### ISSUE TITLE
read Only filesystem..

### ISSUE THREAD

**Issue by thundergreen** [sando38/movim#2]
I just try to run your docker-compose but i get error read only filesystem:

What can I do about it?. I did not change anything but the nginx listen port from 80 to 88.

.....
movim         | rm: cannot remove '/tmp/movim/vendor/ml/json-ld/Test/TestManifestIterator.php': Read-only file system
movim         | rm: cannot remove '/tmp/movim/vendor/ml/json-ld/Test/bootstrap.php': Read-only file system
movim         | rm: cannot remove '/tmp/movim/vendor/ml/json-ld/Test/ValueTest.php': Read-only file system
movim         | rm: cannot remove '/tmp/movim/vendor/ml/json-ld/Test/Fixtures/sample-context.jsonld': Read-only file system
movim         | rm: cannot remove '/tmp/movim/vendor/ml/json-ld/Test/Fixtures/sample-expanded.jsonld': Read-only file system
movim         | rm: cannot remove '/tmp/movim/vendor/ml/json-ld/Test/Fixtures/sample-serialized-document.jsonld': Read-only file system
movim         | rm: cannot remove '/tmp/movim/vendor/ml/json-ld/Test/Fixtures/sample-flattened.jsonld': Read-only file system
movim         | rm: cannot remove '/tmp/movim/vendor/ml/json-ld/Test/Fixtures/sample-compacted.jsonld': Read-only file system
movim         | rm: cannot remove '/tmp/movim/vendor/ml/json-ld/Test/Fixtures/sample-in.jsonld': Read-only file system
movim         | rm: cannot remove '/tmp/movim/vendor/ml/json-ld/Test/Fixtures/dataset.jsonld': Read-only file system
movim         | rm: cannot remove '/tmp/movim/vendor/ml/json-ld/Test/GraphTest.php': Read-only file system
movim         | rm: cannot remove '/tmp/movim/vendor/ml/json-ld/Test/JsonTestCase.php': Read-only file system
movim         | rm: cannot remove '/tmp/movim/vendor/ml/json-ld/Test/W3CTestSuiteTest.php': Read-only file system
movim         | rm: cannot remove '/tmp/movim/vendor/ml/json-ld/GraphInterface.php': Read-only file system
movim         | rm: cannot remove '/tmp/movim/vendor/ml/json-ld/LanguageTaggedString.php': Read-only file system
movim         | rm: cannot remove '/tmp/movim/vendor/ml/json-ld/DocumentFactoryInterface.php': Read-only file system
movim         | rm: cannot remove '/tmp/movim/vendor/ml/json-ld/.devcontainer/Dockerfile': Read-only file system
movim         | rm: cannot remove '/tmp/movim/vendor/ml/json-ld/.devcontainer/devcontainer.json': Read-only file system
movim         | rm: cannot remove '/tmp/movim/vendor/ml/json-ld/composer.json': Read-only file system
movim         | rm: cannot remove '/tmp/movim/vendor/ml/json-ld/Value.php': Read-only file system
movim         | rm: cannot remove '/tmp/movim/vendor/ml/json-ld/Node.php': Read-only file system
movim         | rm: cannot remove '/tmp/movim/vendor/ml/json-ld/TypedValue.php': Read-only file system
movim         | rm: cannot remove '/tmp/movim/vendor/ml/json-ld/JsonLD.php': Read-only file system
movim         | rm: cannot remove '/tmp/movim/vendor/ml/json-ld/DocumentInterface.php': Read-only file system
movim         | rm: cannot remove '/tmp/movim/vendor/ml/json-ld/.github/workflows/ci.yaml': Read-only file system
movim         | rm: cannot remove '/tmp/movim/vendor/ml/json-ld/Exception/InvalidQuadException.php': Read-only file system
movim         | rm: cannot remove '/tmp/movim/vendor/ml/json-ld/Exception/JsonLdException.php': Read-only file system
movim         | rm: cannot remove '/tmp/movim/vendor/ml/json-ld/Graph.php': Read-only file system
movim         | rm: cannot remove '/tmp/movim/vendor/ml/json-ld/NQuads.php': Read-only file system
movim         | rm: cannot remove '/tmp/movim/vendor/ml/json-ld/RemoteDocument.php': Read-only file system
movim         | rm: cannot remove '/tmp/movim/vendor/ml/json-ld/Document.php': Read-only file system
movim         | rm: cannot remove '/tmp/movim/vendor/ml/json-ld/NodeInterface.php': Read-only file system
movim         | rm: cannot remove '/tmp/movim/config/daemon.php': Read-only file system
movim         | rm: cannot remove '/tmp/movim/config/database.php': Read-only file system
movim         | rm: cannot remove '/tmp/movim/config/paths.php': Read-only file system

.....

any idea?

**Comment by thundergreen** [comment]
SOLVED by removing Read only option in docker-compose.yaml

**Comment by sando38** [comment]
Thanks for reporting the issue. 

I commented the `read_only` part in the `docker-compose.yml` example for now. I will check the Dockerfile, which may need an adjustment in the `VOLUME` part, although it works in my setup.

What system do you run? podman, docker?

**Comment by sando38** [comment]
I could reproduce it with using Docker. 

I run my movim with `podman` and `podman` launches automatically a `tmpfs` at `/tmp` when using `read-only` ([Link](https://docs.podman.io/en/latest/markdown/podman-run.1.html#read-only-tmpfs)). `Docker` seems not... 

So if you try with the new image `ghcr.io/sando38/movim:v0.21rc6-r1` which currently builds, it should work now with enabled `read_only: true` in the `docker-compose.yml`.

Otherwise please let me know.

**Comment by thundergreen** [comment]
Hello ..thanks a thousand times ..will try this and report

sando38 ***@***.***> schrieb am So., 19. Feb. 2023, 11:22:
