### ISSUE TITLE
Max Upload size

### ISSUE THREAD

**Issue by thundergreen** [sando38/movim#3]
Hello I saw you have max upload size to 10GB in nginx.conf but my movim will only accet 10MB. Do you know where to change it? Already changes client_max_upload 10G in Server and http part of nginx configs (both) without any success. I gues it is PHP related but I cannot figure out where to find php.ini :( Any hint?

**Comment by sando38** [comment]
From inside the container, if I run
```
$ echo $PHP_INI_DIR
/usr/local/etc/php
```
this should be the location for the `php.ini` file.

It is defined [here](https://github.com/sando38/movim/blob/9b2fca1924fb042e5f3aa9d6826adca271c63271/image/Dockerfile.debian#L46).

**Comment by thundergreen** [comment]
What's the standard value? 10mb?

**Comment by sando38** [comment]
```
$ cat $PHP_INI_DIR/php.ini | grep filesize 
; https://php.net/upload-max-filesize
upload_max_filesize = 2M
```

However, I assume you use `ejabberd`, you need to check your [mod_http_upload](https://docs.ejabberd.im/admin/configuration/modules/#mod-http-upload) and probably need to adjust the default value of 10MB there as well.

**Comment by thundergreen** [comment]
Using prosody with upload of 1tb (just for Testing) but movim always shows 10Mb .let me adjust this php file and report back .but it's strange that in php.ini it's 2 but o get 10 from movim

**Comment by thundergreen** [comment]
I also changes nginx config as well .. your is already a 10G

**Comment by sando38** [comment]
I use `ejabberd` and have 100MB defined in `mod_http_upload` which is also what `movim` shows me. In my config I did not touch the `php.ini` file. It did not prevent me uploading bigger images yet. Let me know, if I can further help you.

**Comment by thundergreen** [comment]
Can't access this file ...read only...:/

**Comment by sando38** [comment]
Yeah, start up your container without the `read_only: true` flag and see if changing that file will actually have an effect. If yes, we can see how we can tackle that challenge.

**Comment by thundergreen** [comment]
We have to add nano in dockerfile will make a pull request

sando38 ***@***.***> schrieb am Mi., 22. Feb. 2023, 13:37:

**Comment by thundergreen** [comment]
well this has nothing to do with php.ini. I will try to start nginx proxy server to see if my synology proxy limits uploads to 10MB

**Comment by thundergreen** [comment]
GOT IT WORKING: nOTHING RELATED TO THIS REPO   :)
